---

- name: Create Certs | random wait
  pause:
    seconds: "{{ (1,4) | random }}"

- name: Create Certs | Show vars certificate directive
  debug:
    var: item
  with_items: "{{ certificate_directive | dict2items }}"

- name: Create Certs | Create directory tree
  file:
    state: directory
    dest: "{{ item }}"
  with_items: "{{ dir_list }}"

- name: Create Certs | Create cfssl configurations
  copy:
    content: "{{ item.value.configuration | to_nice_json }}"
    dest: "{{ item.value.configurations_path }}"
  with_items: "{{ certificate_directive | dict2items }}"

- name: Create Certs | Debug Show vars command_run
  debug:
    var: item
  with_items: "{{ command_run | dict2items }}"

- name: Create Certs | CertDir
  file:
    state: directory
    dest: "{{ item.value.chdir }}"
  with_items: "{{ command_run | dict2items }}"

- name: Create Certs |  Use cfssl for create certificates
  shell: "{{ item.value.shell }}"
  args:
    chdir: "{{ item.value.chdir }}/"
    creates: "{{ item.value.creates }}"
  delegate_to: "{{ item.value.delegate_to }}"
  with_items: "{{ command_run | dict2items }}"
  tags:
    - skip_ansible_lint
