---
#- name: random wait
#  pause:
#    seconds: "{{ (3,15) | random }}"

# - name: Debug
#   debug:
#     var: item.value.chdir
#   with_items: "{{ command_run | dict2items }}"
# 
# - name: show vars
#   debug:
#     msg: "{{ node_certificate.configuration | to_json }}"

- name: show vars
  debug: 
    var: item
  with_items: "{{ certificate_directive | dict2items }}"

- name: conf | Create directory tree
  file:
    state: directory
    dest: "{{ item }}"
  with_items: "{{ dir_list }}"

- name: conf | Create cfssl configurations
  copy:
    content: "{{ item.value.configuration | to_nice_json }}"
    dest: "{{ item.value.configurations_path }}"
  with_items: "{{ certificate_directive | dict2items }}"

- name: show vars
  debug: 
    var: item
  with_items: "{{ command_run | dict2items }}"

- name: create CertDir
  file:
    state: directory
    dest: "{{ item.value.chdir }}"
  with_items: "{{ command_run | dict2items }}"
  
- name: Create Certs |  
  shell: "{{ item.value.shell }}"
  args:
    chdir: "{{ item.value.chdir }}/"
    creates: "{{ item.value.creates }}"
  delegate_to: "{{ item.value.delegate_to }}"
  with_items: "{{ command_run | dict2items }}"
