---

- name: just install cfssl
  hosts: node-1
  gather_facts: true
  roles:
    - role: ansible-cfssl
      install: True
      configure: True

# - name: install and configure
#   hosts: configure
#   gather_facts: true
#   roles:
#     - role: ansible-cfssl
#       install: True
#       configure: False
